Repository apache/incubator-openwhisk-runtime-docker, pull requests merged in 2018-05, with the labels that each got.

#28 Add the licenses of the dependencies into LICENSE
  LICENSE.txt
  licenses/LICENSE-flask.txt
  licenses/LICENSE-gevent.txt
  licenses/LICENSE-pip.txt
  licenses/LICENSE-python.txt
  licenses/LICENSE-setuptools.txt
  licenses/LICENSE-six.txt
Labels: review

#33 Add ASF license headers to all Scala .conf files.
  .scalafmt.conf
  tests/src/test/resources/application.conf
Labels: apache

#36 Fix markdown files with a typo. in the Hash license header.
  CONTRIBUTING.md
  README.md
  core/CHANGELOG.md
  core/actionProxy/README.md
  gradle/README.md
  sdk/docker/README.md
  sdk/docker/buildAndPush.sh
  tests/dat/blackbox/badaction/README.md
  tests/dat/blackbox/badproxy/README.md
Labels: apache, documentation

#38 Fix travis yaml file asf header, change to mini.
  .travis.yml
Labels: apache, review

#39 Last files to need ASF License headers.
  ansible/environments/local/group_vars/all
  build.gradle
  core/actionProxy/build.gradle
  gradle/docker.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/docker/build.gradle
  settings.gradle
  tests/build.gradle
  tests/dat/blackbox/badaction/build.gradle
  tests/dat/blackbox/badproxy/build.gradle
Labels: apache, review

#40 Fix example.c to have correct ASF license header.
  sdk/docker/example.c
Labels: apache

#41 Fix bad Dockerfile license and use ASF release config.
  core/actionProxy/Dockerfile
  sdk/docker/Dockerfile
  tests/dat/blackbox/badaction/Dockerfile
  tests/dat/blackbox/badproxy/Dockerfile
  tools/travis/build.sh
Labels: apache
